testcontainers/testcontainers-rs-modules-community

src/dynamodb_local/mod.rs, src/zookeeper/mod.rs
Additionally it solves the issues with unreliable testing, so I've enabled it.
Closes #4
=> refactor(zookeper): use bitnami image

Cargo.toml, src/dynamodb_local/mod.rs
It's 7 years old crate which doesn't bring any benefits for the modules.
=> chore(deps): remove spectral

src/postgres/mod.rs, src/rabbitmq/mod.rs
Also removes unnecessary test
Relates to #2
=> docs: add documentation for postgres image

src/elasticmq/mod.rs
We need to update the image tag, it's pretty outdated and creates issues in CI due to client updates.
I marked the PR as breaking, because we do change the major version of image
=> chore(deps)!: update `elasticmq` default image version

Cargo.toml, examples/mssql_server.rs, src/lib.rs, src/mssql_server/mod.rs
This PR adds a Microsoft SQL Server module based on the official Docker images.
https://hub.docker.com/_/microsoft-mssql-server
Thanks!
=> feat: add `Microsoft SQL Server` module

Cargo.toml, src/orientdb/mod.rs
The client library seems not well maintained and contains pretty outdated dependencies. For testing purposes using the REST-API works well enough.
`retry` is used to stabilise the test, since at least locally it took the container some time after start-up to accept REST-API requests sometimes. I couldn't find out a way to wait exactly for the time when the API is ready. According to the container logs the start-up is finished.
Closes #38
=> refactor(orientdb): use rest-api instead of client library

Cargo.toml, examples/surrealdb.rs, src/lib.rs, src/surrealdb/mod.rs
This add `surrealdb` module. The version of `surrealdb` crate is fixed to a specific commit which bumps `rustls` version and enable compatibility with other crates. I will looking for the next release to switch on the tagged version.
And thanks for your work!
=> feat: add `SurrealDb` module

Cargo.toml
We don't need the git-version anymore, the patch with fix has been released.
=> chore(deps): update `surrealdb` client for tests

Cargo.toml, src/zookeeper/mod.rs
Zookeeper had too flacky test and was disabled because of it. Previous client behaves unstable and caused compilation issues time-to-time in CI
=> test(zookeeper): re-enable test and change the client

.github/workflows/ci.yml
rust-cache should help a lot
However, a lot of time also consumed for docker-image pulling in CI, but it's trickier to improve
=> build(ci): add rust-cache

.github/workflows/ci.yml
=> build(ci): enable `clean-per-run` for `cargo hack` in tests

.github/workflows/ci.yml
Test-suite consumes a lot of disk-space and we encounter `no space left on divice` quite often. Especially under nightly and taking docker-images (not all of them pre-cached by GH) into account
This PR should fix that
=> build(ci): maximize disk space for tests

Cargo.toml, src/consul/mod.rs, src/lib.rs
HashiCorp Consul
https://www.consul.io/
=> feat: add consul module

Cargo.toml, src/cncf_distribution/mod.rs, src/lib.rs
This PR adds a module for CNCF Distrubution, a registry for container images. Some basic testing is included.
=> feat: add `CNCF Distribution` module

CONTRIBUTING.md
Contributes to #2 
Adds some general contribution guidelins for this project. I've used some other testcontainers projects (`java`, `ruby`, `python`, `rust`) as reference.
=> docs: adds contribution guidelines

examples/localstack.rs
Closes #131, where I discovered the `localstack` example is broken when running:
```
cargo run --example localstack --features="localstack" 
```
Some research brought me to [awslabs/aws-sdk-rust#1138](https://github.com/awslabs/aws-sdk-rust/issues/1138), which uncovered that `create_bucket` is broken here because `localstack` uses the soon-to-be-deprecated ["path-style"](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) address style rather than the newer "virutal-hosted" style.
I reworked the configuration in the example to set `force_path_style(true)`, which fixes `create_bucket`. The example now runs successfully.
I also updated the `BehaviorVersion`, because the currently referenced one is now deprecated and was causing a warning.
=> docs(localstack): fix localstack example by setting `force_path_style`

src/clickhouse/mod.rs, src/cockroach_db/mod.rs, src/consul/mod.rs, src/dynamodb_local/mod.rs, src/elastic_search/mod.rs, src/elasticmq/mod.rs, src/google_cloud_sdk_emulators/mod.rs, src/hashicorp_vault/mod.rs, src/kafka/mod.rs, src/kwok/mod.rs, src/localstack/mod.rs, src/mariadb/mod.rs, src/minio/mod.rs, src/mongo/mod.rs, src/mssql_server/mod.rs, src/mysql/mod.rs, src/nats/mod.rs, src/oracle/free.rs, src/orientdb/mod.rs, src/parity_parity/mod.rs, src/postgres/mod.rs, src/redis/stack.rs, src/redis/standalone.rs, src/solr/mod.rs, src/surrealdb/mod.rs, src/trufflesuite_ganachecli/mod.rs, src/victoria_metrics/mod.rs, src/zookeeper/mod.rs
This is a followup to https://github.com/testcontainers/testcontainers-rs-modules-community/pull/154#discussion_r1660223826
(I don't have a real usecase for this. Just thought that more consistency can't hurt)
`Neo4jImage` is ommited, as `ContainerState` does not implement `Clone`.
=> chore: made deriving `Clone` consistent

Cargo.toml, src/clickhouse/mod.rs, src/elastic_search/mod.rs, src/k3s/mod.rs, src/kafka/mod.rs, src/kwok/mod.rs, src/meilisearch/mod.rs, src/oracle/free.rs, src/surrealdb/mod.rs
This is part of the larger documentation overhall initaltive https://github.com/testcontainers/testcontainers-rs-modules-community/issues/2
This is breaking in the sense that some containers ports were `u16` before..
Don't know how we should handle this..
=> docs: documented all ports which containers at least expose

Cargo.toml, src/zookeeper/mod.rs
- I am soo sorry.
Idk why, but apparenty I forgot to run `cargo test` on https://github.com/testcontainers/testcontainers-rs-modules-community/pull/184 while documenting this on my commute 👀 
- I also included the mongo-example patch
=> fix: doc-test failures

.github/workflows/ci.yml
In CI, we are currently using `actions-rs` variant of steps. [They are pretty deprecated.](https://github.com/actions-rs)
This resolves these, which I noticed during #186's [actions run](https://github.com/testcontainers/testcontainers-rs-modules-community/actions/runs/10481678682?pr=186):
There are a ton of options avaliable, maybe even a `rust-lang`-action https://github.com/rust-lang/rustup/issues/3409
Currently, that is not the case.
(open to alternatives if you prefer another one more ^^)
> [!NOTE]
> This is not without downside as replacing `uses: actions-rs/cargo` with `run: cargo ...` does not come with the annotations that github displays f. ex. here from another repo where I recently also contributed this:
> ![image](https://github.com/user-attachments/assets/6b61c970-800d-4489-8 …
=> ci: changed from `actions-rs` to a more maintained CI alternative

rustfmt.toml, src/cncf_distribution/mod.rs, src/k3s/mod.rs, src/kwok/mod.rs, src/mariadb/mod.rs, src/mosquitto/mod.rs, src/mysql/mod.rs, src/neo4j/mod.rs, src/rabbitmq/mod.rs, src/redis/standalone.rs, src/solr/mod.rs, src/surrealdb/mod.rs, src/victoria_metrics/mod.rs, src/zookeeper/mod.rs
`format_code_in_doc_comments` is a nightly `rustfmt` feature. (tracking issue: https://github.com/rust-lang/rustfmt/issues/3348)
I think this might be helpfull.
Usually, I would not consider this being an option, but given that already some other `rustfmt` feature are enabled... 😉
=> docs: enable `rustfmt` for doc comments

Cargo.toml, examples/openldap.rs, src/lib.rs, src/openldap/mod.rs
I noticed that there currently is not LDAP testcontainer.
Similar to the [go testontainer modules](https://github.com/testcontainers/testcontainers-go/blob/c44b1b2ed935455fa222f122a7474efe309f641c/modules/openldap/openldap.go#L128C19-L128C41), I chose the [`bitnami/openldap`](https://github.com/bitnami/containers/blob/main/bitnami/openldap/README.md) containers.
Similar to https://github.com/testcontainers/testcontainers-rs-modules-community/pull/178, this PR includes the mongodb-example-fix.
=> feat: added an `OpenLDAP` testcontainer module

src/google_cloud_sdk_emulators/mod.rs, src/kafka/apache.rs, src/redis/mod.rs, src/solr/mod.rs
in https://github.com/testcontainers/testcontainers-rs-modules-community/pull/183 I apparently skipped a few ports.
=> this adds the nessesary docs for the ports
=> docs: complete the `*_PORT` documentation

src/kafka/apache.rs, src/neo4j/mod.rs
The neo4j plugins are currently not documented.
This changes that.
The varying level of depth is dependent on what the library put on their wiki site (sometimes slightly edited to fit into our docs).
Part of the #2 effort
=> docs: documents the neo4j plugins

src/mssql_server/mod.rs
It's realted to recent update of GH workers and similar fix was applied in Go modules: https://github.com/testcontainers/testcontainers-go/pull/2786
=> fix(mssql): update version to fix crashes in CI

examples/mssql_server.rs, src/mssql_server/mod.rs
- EULA: I've noticed the default, while it's necessary to do explicitly. Separate method has been added (might be explicit
- Make default password publicly available
=> fix(mssql)!: make EULA acception explicit

src/cockroach_db/mod.rs
Continuing the work to make https://github.com/testcontainers/testcontainers-rs-modules-community/issues/2 happen
=> docs: add missing CockroachDB docs

.github/workflows/ci.yml, Cargo.toml, src/lib.rs, src/pulsar/mod.rs
This PR adds module for [Apache Pulsar](https://pulsar.apache.org/)
=> feat: add `Pulsar` module

Cargo.toml, src/gitea/app.ini, src/gitea/mod.rs, src/lib.rs
This is a module for `Gitea` self-hostded git server.
It's quite usefull to test various git clients with http/https/ssh access to public and private git repos.
Gitea documentation: https://docs.gitea.com/
Gitea repo: https://github.com/go-gitea/gitea
=> feat: add Gitea module

src/mosquitto/mod.rs, src/solr/mod.rs
Fixes clippy warnings that are currently failing the build since rust-version 1.83.0
=> fix: fix clippy errors

src/lib.rs, src/localstack/mod.rs, src/localstack/pro.rs
PR adds a "pro" variant of the existing [LocalStack](https://docs.rs/testcontainers-modules/latest/testcontainers_modules/localstack/struct.LocalStack.html) image.
=> feat: add "pro" variant for LocalStack image

examples/nats.rs, src/nats/mod.rs
NATS has a built-in persistence engine called JetStream which enables messages to be stored and replayed at a later time.
https://docs.nats.io/nats-concepts/jetstream
=> feat: allow enabling jetstream for nats

src/anvil/mod.rs
Following the suggestion made in [discussion here](https://github.com/testcontainers/testcontainers-rs-modules-community/pull/275#discussion_r1929599307) this PR provides a `latest` method on the [Foundry](https://github.com/foundry-rs/foundry) [Anvil](https://github.com/foundry-rs/foundry/tree/master/crates/anvil) node implementation:
```rust
let node = AnvilNode::latest().start().await?;
```
=> chore(anvil): add method latest to anvil node impl

src/gitea/mod.rs
The test was broken in CI, but may work locally (on MacOS for example). In CI it fails with: `self-signed certificate`
It's because of different behavior in `rust-native-tls` depending on the platform. This PR eliminates the issue via explicit usage of rustls. Alternative would be to disable cert verification, but it means test would be useless.
Closes #273
=> test(gitea): fix broken test in CI

Cargo.toml
arrow-arith bug report: https://github.com/apache/arrow-rs/issues/7196
You don't want to actually restrict the Chrono version since your deps need to choose their own workaround, but this will hopefully fix CI.
See #305 for an alternative.
=> chore(deps): pin `chrono` as a dev-dep to fix `arrow-arith` compilation failure

src/minio/mod.rs
It seems like at some point in the last 3 years MinIO switched from writing startup messages on stdou to stderr. I couldn't find a `WaitFor::either()` to keep the old version as the default, so I bumped it to the latest released version.
This update is necessary for folks to be able to use a modern or different tag with `ImageExt`.
=> feat(minio)!: support newest MinIO versions

Cargo.toml, src/surrealdb/mod.rs
This is incompatible update because requires appropriate client.
For the users of surreal v1 it's still possible to use an old version of client and tag customization
=> feat(surrealdb)!: support surrealdb v2

examples/localstack.rs, src/localstack/mod.rs
Fixes the following error:
error: use of deprecated associated function `aws_config::BehaviorVersion::v2024_03_28`: Superseded by v2025_01_17, which updates the default HTTPS client stack.
=> fix: lint error

src/anvil/mod.rs
`stable` image seems to be frequently updated and this wasn't a really good experience
We generally prefer to avoid versions that frequently updated. It's better to keep the version under control - otherwise easy to break user's code
=> fix(anvil): switch to specified version isntead of hashed `stable`

src/consul/mod.rs
This should be the last piece where we don't have docs
Resolves https://github.com/testcontainers/testcontainers-rs-modules-community/issues/2
=> docs: add a docstring for the last missing function `Consul::with_local_config`
